# -----------------------------------------------------------------------------
# Approved project design messages
# -----------------------------------------------------------------------------
# these are board presets from Avnet for microzed
set_msg_config -new_severity INFO -id {PSU-1} -string {{CRITICAL WARNING: [PSU-1]  Parameter : PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_0 has negative value -0.073 . PS DDR interfaces might fail when entering negative DQS skew values.}}
set_msg_config -new_severity INFO -id {PSU-2} -string {{CRITICAL WARNING: [PSU-2]  Parameter : PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_1 has negative value -0.072 . PS DDR interfaces might fail when entering negative DQS skew values.}}

# these don't appear to affect anything
set_msg_config -new_severity INFO -id {BD 41-1731} -string {{WARNING: [BD 41-1731] Type mismatch between connected pins: /clk_wiz_0/clk_out1(clk) and /lotus_bsc_0/CLK_120(undef)}}
set_msg_config -new_severity INFO -id {BD 41-927} -string {{WARNING: [BD 41-927] Following properties on pin /lotus_bsc_0/LVDS_CLK_N have been updated from connected ip. They may not be synchronized with cell properties. You can set property on pin directly to confirm the value and resolve the warning.}}
set_msg_config -new_severity INFO -id {BD 41-927} -string {{WARNING: [BD 41-927] Following properties on pin /lotus_bsc_0/LVDS_CLK_P have been updated from connected ip. They may not be synchronized with cell properties. You can set property on pin directly to confirm the value and resolve the warning.}}
set_msg_config -new_severity INFO -id {BD 41-927} -string {{WARNING: [BD 41-927] Following properties on pin /lotus_bsc_0/s00_axi_aclk have been updated from connected ip. They may not be synchronized with cell properties. You can set property on pin directly to confirm the value and resolve the warning.}}
set_msg_config -new_severity INFO -id {BD 41-927} -string {{WARNING: [BD 41-927] Following properties on pin /lotus_bsc_0/ITO_CLK have been updated from connected ip. They may not be synchronized with cell properties. You can set property on pin directly to confirm the value and resolve the warning.}}
set_msg_config -new_severity INFO -id {BD 41-927} -string {{WARNING: [BD 41-927] Following properties on pin /lotus_spi_0/s00_axi_aclk have been updated from connected ip. They may not be synchronized with cell properties. You can set property on pin directly to confirm the value and resolve the warning.}}

# ignore autogenerated stuff
set_msg_config -new_severity INFO -id {IP_Flow 19-4994} -string {{WARNING: [IP_Flow 19-4994] Overwriting existing constraint file} {lotus_auto_pc_0_ooc.xdc}}

# called as a result of export_simulation
set_msg_config -new_severity INFO -id {Vivado 12-3672} -string {{WARNING: [Vivado 12-3672] The is_managed property should only be queried on the file object representing this IP. Use the get_files command to access file objects.}}
set_msg_config -new_severity INFO -id {Vivado 12-3670} -string {{WARNING: [Vivado 12-3670] The generate_synth_checkpoint property should only be queried on the file object representing this IP. Use the get_files command to access file objects.}}

# global include file is included multiple times
set_msg_config -new_severity INFO -id {IP_Flow 19-1971} -string {{WARNING: [IP_Flow 19-1971] File named "../../../rtl_src/lotus_defines.v" already exists in file group "xilinx_anylanguagebehavioralsimulation", cannot add it again.}}
set_msg_config -new_severity INFO -id {IP_Flow 19-1971} -string {{WARNING: [IP_Flow 19-1971] File named "../../../rtl_src/lotus_defines.v" already exists in file group "xilinx_anylanguagesynthesis", cannot add it again.}}

# ignore project management stuff
set_msg_config -new_severity INFO -id {IP_Flow 19-731} -string {{WARNING: [IP_Flow 19-731] File Group 'xilinx_anylanguagesynthesis (Synthesis)': } {file path is not relative to the IP root directory.}}
set_msg_config -new_severity INFO -id {IP_Flow 19-731} -string {{WARNING: [IP_Flow 19-731] File Group 'xilinx_anylanguagebehavioralsimulation (Simulation)': } {file path is not relative to the IP root directory.}}

# max path is around 150 characters (not close to 260).
set_msg_config -new_severity INFO -id {IP_Flow 19-4995} -string {{[IP_Flow 19-4995] The host OS only allows 260 characters in a normal path. The IP cache path is more than 80 characters. If you experience issues with IP caching, please consider changing the IP cache to a location with a shorter path. Alternately consider using the OS subst command to map part of the path to a drive letter.}}

# -----------------------------------------------------------------------------
# Approved synthesis messages
# -----------------------------------------------------------------------------
# Don't limit quanitity of synthesis messages. Escalate said suppression.
set_msg_config -limit 1000 -id {Synth 8-3331}
set_msg_config -new_severity WARNING -id {Common 17-14}

# our code doesn't use this so must be an automatic step in synth_design
set_msg_config -new_severity INFO -id {Common 17-576} -string {{WARNING: [Common 17-576] 'use_project_ipc' is deprecated. This option is deprecated and no longer used.}}

# Don't worry about AXI interconnect internals. See Vivado schematics of
# elaborated design (not synthesized design) for details. m0x_couplers appear
# to be pass-throughs so global clock and reset signals aren't used.
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design lotus_ps7_0_axi_periph_0 has unconnected port M00_ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design lotus_ps7_0_axi_periph_0 has unconnected port M01_ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design lotus_ps7_0_axi_periph_0 has unconnected port M00_ARESETN}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design lotus_ps7_0_axi_periph_0 has unconnected port M01_ARESETN}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design s00_couplers_imp_KAR85Y has unconnected port M_ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design s00_couplers_imp_KAR85Y has unconnected port M_ARESETN}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design m00_couplers_imp_8PA7LP has unconnected port M_ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design m00_couplers_imp_8PA7LP has unconnected port M_ARESETN}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design m00_couplers_imp_8PA7LP has unconnected port S_ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design m00_couplers_imp_8PA7LP has unconnected port S_ARESETN}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design m01_couplers_imp_1A8MUXH has unconnected port M_ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design m01_couplers_imp_1A8MUXH has unconnected port M_ARESETN}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design m01_couplers_imp_1A8MUXH has unconnected port S_ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design m01_couplers_imp_1A8MUXH has unconnected port S_ARESETN}}

# Reported when there are no constraints for a top-level cell
set_msg_config -new_severity INFO -id {Constraints 18-5210} -string {{WARNING: [Constraints 18-5210] No constraints selected for write.}}

# Unused flip-flops in RTL
set_msg_config -new_severity INFO -id {Synth 8-3936} -string {{WARNING: [Synth 8-3936] Found unconnected internal register 'I_lotus_sync_a2b/B_DATA_reg' and it is trimmed from '32' to '5' bits.}}
set_msg_config -new_severity INFO -id {Synth 8-6014} -string {{WARNING: [Synth 8-6014] Unused sequential element inst/I_lotus_table_mover/TXFER_DONE_reg was removed.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (write_addr_pp_reg[0]) is unused and will be removed from module lotus_active_mem.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (write_addr_pp_reg[1]) is unused and will be removed from module lotus_active_mem.}}
#   - CH1_WR_ACK_reg is a special case for lotus_spi only (not lotus_bsc)
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (CH1_WR_ACK_reg) is unused and will be removed from module lotus_active_mem.}}
#   - MISO_1 datapath is unused
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (RDATA_1_reg[15]) is unused and will be removed from module lotus_spi_controller.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (RDATA_1_reg[14]) is unused and will be removed from module lotus_spi_controller.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (RDATA_1_reg[13]) is unused and will be removed from module lotus_spi_controller.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (RDATA_1_reg[12]) is unused and will be removed from module lotus_spi_controller.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (RDATA_1_reg[11]) is unused and will be removed from module lotus_spi_controller.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (RDATA_1_reg[10]) is unused and will be removed from module lotus_spi_controller.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (RDATA_1_reg[9]) is unused and will be removed from module lotus_spi_controller.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (RDATA_1_reg[8]) is unused and will be removed from module lotus_spi_controller.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (RDATA_1_reg[7]) is unused and will be removed from module lotus_spi_controller.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (RDATA_1_reg[6]) is unused and will be removed from module lotus_spi_controller.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (RDATA_1_reg[5]) is unused and will be removed from module lotus_spi_controller.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (RDATA_1_reg[4]) is unused and will be removed from module lotus_spi_controller.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (RDATA_1_reg[3]) is unused and will be removed from module lotus_spi_controller.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (RDATA_1_reg[2]) is unused and will be removed from module lotus_spi_controller.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (RDATA_1_reg[1]) is unused and will be removed from module lotus_spi_controller.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (RDATA_1_reg[0]) is unused and will be removed from module lotus_spi_controller.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (I_lotus_spi_io/I_IBUF_MISO[1]) is unused and will be removed from module lotus_spi.}}
#   - rfu bit in cmd fifo is unused
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (fifo_reg[15][27]) is unused and will be removed from module lotus_fifo.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (fifo_reg[14][27]) is unused and will be removed from module lotus_fifo.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (fifo_reg[13][27]) is unused and will be removed from module lotus_fifo.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (fifo_reg[12][27]) is unused and will be removed from module lotus_fifo.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (fifo_reg[11][27]) is unused and will be removed from module lotus_fifo.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (fifo_reg[10][27]) is unused and will be removed from module lotus_fifo.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (fifo_reg[9][27]) is unused and will be removed from module lotus_fifo.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (fifo_reg[8][27]) is unused and will be removed from module lotus_fifo.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (fifo_reg[7][27]) is unused and will be removed from module lotus_fifo.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (fifo_reg[6][27]) is unused and will be removed from module lotus_fifo.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (fifo_reg[5][27]) is unused and will be removed from module lotus_fifo.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (fifo_reg[4][27]) is unused and will be removed from module lotus_fifo.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (fifo_reg[3][27]) is unused and will be removed from module lotus_fifo.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (fifo_reg[2][27]) is unused and will be removed from module lotus_fifo.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (fifo_reg[1][27]) is unused and will be removed from module lotus_fifo.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (fifo_reg[0][27]) is unused and will be removed from module lotus_fifo.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (cmd_reg[27]) is unused and will be removed from module lotus_spi_fsm.}}
#   - Bits 31:13, 63:45, and 95:77 of RDATA in onewire controller get constant zeros so they are merged and then the final one remaining (bit 95) is removed
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{[Synth 8-3332] Sequential element (RDATA_reg[95]) is unused and will be removed from module lotus_onewire_controller.}}

# Unused ports
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design lotus_laser_control has unconnected port CONTROL}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design lotus_spi_fsm has unconnected port SPI_CONTROL}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design lotus_spi_fsm has unconnected port RDATA_1}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design lotus_active_mem has unconnected port CH0_RD_ADDR[1]}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design lotus_active_mem has unconnected port CH0_RD_ADDR[0]}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design lotus_axi_interface has unconnected port S_AXI_AWPROT}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design lotus_axi_interface has unconnected port S_AXI_ARPROT}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design lotus_lotus_bsc_0_0 has unconnected port s00_axi_awprot}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design lotus_lotus_bsc_0_0 has unconnected port s00_axi_arprot}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design lotus_spi has unconnected port s00_axi_awprot}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design lotus_spi has unconnected port s00_axi_arprot}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design lotus_core has unconnected port CONFIG}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design lotus_core has unconnected port CONTROL}}
#   - Laser controller config bits
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design lotus_laser_control has unconnected port CONFIG[31]}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design lotus_laser_control has unconnected port CONFIG[30]}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design lotus_laser_control has unconnected port CONFIG[29]}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design lotus_laser_control has unconnected port CONFIG[28]}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design lotus_laser_control has unconnected port CONFIG[27]}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design lotus_laser_control has unconnected port CONFIG[26]}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design lotus_laser_control has unconnected port CONFIG[25]}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design lotus_laser_control has unconnected port CONFIG[24]}}

# These constraints only apply to implementation but I can't directly filter between synth and impl
#set_msg_config -new_severity INFO -id {Vivado 12-508} -string {{WARNING: [Vivado 12-508] No pins matched 'lotus_i/lotus_0/inst/}}
#set_msg_config -new_severity INFO -id {Vivado 12-180} -string {{WARNING: [Vivado 12-180] No cells matched 'lotus_i/lotus_0/inst/}}
#set_msg_config -new_severity INFO -id {Project 1-498} -string {{WARNING: [Project 1-498] One or more constraints failed evaluation while reading constraint file [C:/Users/twilliamson/git_repos/zynq_dev/constraints/lotus_constraints.xdc] and the design contains unresolved black boxes. These constraints will be read post-synthesis (as long as their source constraint file is marked as used_in_implementation) and should be applied correctly then. You should review the constraints listed in the file [.Xil/lotus_wrapper_propImpl.xdc] and check the run log file to verify that these constraints were correctly applied.}}

# -----------------------------------------------------------------------------
# Approved implementation messages
# -----------------------------------------------------------------------------
set_msg_config -new_severity INFO -id {Constraints 18-550} -string {{WARNING: [Constraints 18-550] Could not create 'IBUF_LOW_PWR' constraint because net 'lotus_i/clk_wiz_0/clk_in1' is not directly connected to top level port. Synthesis is ignored for c:/Users/twilliamson/git_repos/zynq_dev/vivado_projects/lotus/lotus.srcs/sources_1/bd/lotus/ip/lotus_clk_wiz_0_0/lotus_clk_wiz_0_0/lotus_clk_wiz_0_0.edf but preserved for implementation. [c:/Users/twilliamson/git_repos/zynq_dev/vivado_projects/lotus/lotus.srcs/sources_1/bd/lotus/ip/lotus_clk_wiz_0_0/lotus_clk_wiz_0_0/lotus_clk_wiz_0_0.edf:314]}}
set_msg_config -new_severity INFO -id {Opt 31-32} -string {{WARNING: [Opt 31-32] Removing redundant IBUF since it is not being driven by a top-level port. lotus_i/clk_wiz_0/inst/clkin1_ibufg}}
