# Launch clock
#   - The PS7 XDC files create the fabric clock for us. Retrieve it here.
set launch_clock [get_clocks clk_fpga_0]

# Capture clock
#   - CLK_90 is generated by the MMCM and forwarded by the ODDRs. That is, for
#     now, the same MMCM output is used for both RX and TX capture clocks.
create_generated_clock \
    -name clk_rx_lvds \
    -divide_by 1 \
    -source [get_pins delorean_i/delorean_lcm_0/inst/U_delorean_lcm_io_mlvds_rx/U_ODDR_LVDS_CLK/C] \
    [get_ports RX_LVDS_CLK_P]

create_generated_clock \
    -name clk_tx_lvds \
    -divide_by 1 \
    -source [get_pins delorean_i/delorean_lcm_0/inst/U_delorean_lcm_io_mlvds_tx/U_ODDR_LVDS_CLK/C] \
    [get_ports TX_LVDS_CLK_P]

# Output delay constraints
set tsu_r              1.000;   # Destination device setup time requirement for rising edge
set thd_r              1.000;   # Destination device hold time requirement for rising edge
set tsu_f              1.000;   # Destination device setup time requirement for falling edge
set thd_f              1.000;   # Destination device hold time requirement for falling edge
set trce_dly_max       0.000;   # Maximum board trace delay
set trce_dly_min       0.000;   # Minimum board trace delay

set capture_clock [get_clocks clk_rx_lvds]
set output_ports [get_ports RX_LVDS_DATA*]
set_output_delay -clock $capture_clock -max [expr $trce_dly_max + $tsu_r] [get_ports $output_ports]
set_output_delay -clock $capture_clock -min [expr $trce_dly_min - $thd_r] [get_ports $output_ports]
set_output_delay -clock $capture_clock -max [expr $trce_dly_max + $tsu_f] [get_ports $output_ports] -clock_fall -add_delay
set_output_delay -clock $capture_clock -min [expr $trce_dly_min - $thd_f] [get_ports $output_ports] -clock_fall -add_delay

set capture_clock [get_clocks clk_tx_lvds]
set output_ports [get_ports TX_LVDS_DATA*]
set_output_delay -clock $capture_clock -max [expr $trce_dly_max + $tsu_r] [get_ports $output_ports]
set_output_delay -clock $capture_clock -min [expr $trce_dly_min - $thd_r] [get_ports $output_ports]
set_output_delay -clock $capture_clock -max [expr $trce_dly_max + $tsu_f] [get_ports $output_ports] -clock_fall -add_delay
set_output_delay -clock $capture_clock -min [expr $trce_dly_min - $thd_f] [get_ports $output_ports] -clock_fall -add_delay

# Setup analysis
#   - The timing analyzer creates four permutations of launch-capture paths. For
#     setup timing, the capture clock edge is the first edge after the launch
#     clock edge (i.e. multicycle = 1, by default). Note: eventhough we use mode
#     "SAME_EDGE" for ODDR, the tool assumes data is launched on rising and
#     falling edges of the system clock.
#       1. launch: $launch_clock rise at 0.0 ns, capture: $capture_clock rise at 2.5 ns   <- desired
#       2. launch: $launch_clock rise at 0.0 ns, capture: $capture_clock fall at 7.5 ns   <- false
#       3. launch: $launch_clock fall at 5.0 ns, capture: $capture_clock fall at 7.5 ns   <- desired
#       4. launch: $launch_clock fall at 5.0 ns, capture: $capture_clock rise at 12.5 ns  <- false
set capture_clock [get_clocks clk_rx_lvds]
set_false_path -setup -rise_from $launch_clock -fall_to $capture_clock
set_false_path -setup -fall_from $launch_clock -rise_to $capture_clock

set capture_clock [get_clocks clk_tx_lvds]
set_false_path -setup -rise_from $launch_clock -fall_to $capture_clock
set_false_path -setup -fall_from $launch_clock -rise_to $capture_clock

# Hold analysis
#   - The timing analyzer creates four permutations of launch-capture paths. For
#     hold checks, the tool uses the same launch edges from the setup checks;
#     however, it uses the capture edge that is one capture clock period earlier
#     than the capture edge for setup checks (i.e. multicycle = 0, by default).
#   - Equivalently, we can do hold analysis by keeping the capture edges and
#     delaying the launch edges, which is more intuitive since we are concerned
#     about the captured data being corrupted by the coming launch edge. Note:
#     the tool still uses the convention that the path starts from the launch
#     edge (i.e. "from" <-> "launch" and "to" <-> "capture").
#       1. capture: $capture_clock rise at 2.5 ns, next launch: $launch_clock fall at  5.0 ns   <- desired
#       2. capture: $capture_clock rise at 2.5 ns, next launch: $launch_clock rise at 10.0 ns   <- false
#       3. capture: $capture_clock fall at 7.5 ns, next launch: $launch_clock rise at 10.0 ns   <- desired
#       4. capture: $capture_clock fall at 7.5 ns, next launch: $launch_clock fall at 15.0 ns   <- false
set capture_clock [get_clocks clk_rx_lvds]
set_false_path -hold -rise_from $launch_clock -rise_to $capture_clock
set_false_path -hold -fall_from $launch_clock -fall_to $capture_clock

set capture_clock [get_clocks clk_tx_lvds]
set_false_path -hold -rise_from $launch_clock -rise_to $capture_clock
set_false_path -hold -fall_from $launch_clock -fall_to $capture_clock

# Tri-state enable timing is not important (static during normal operation)
set_false_path \
    -from [get_pins {delorean_i/delorean_lcm_0/inst/U_delorean_lcm_io_mlvds_rx/U_ODDR_LVDS_DATA_EN[*]/C}] \
    -to [get_ports RX_LVDS_DATA*]

set_false_path \
    -from [get_pins {delorean_i/delorean_lcm_0/inst/U_delorean_lcm_io_mlvds_tx/U_ODDR_LVDS_DATA_EN[*]/C}] \
    -to [get_ports TX_LVDS_DATA*]
