# -----------------------------------------------------------------------------
# Approved project design messages
# -----------------------------------------------------------------------------
# these are board presets from Avnet for microzed
set_msg_config -new_severity INFO -id {PSU-1} -string {{CRITICAL WARNING: [PSU-1]  Parameter : PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_0 has negative value -0.073 . PS DDR interfaces might fail when entering negative DQS skew values.}}
set_msg_config -new_severity INFO -id {PSU-2} -string {{CRITICAL WARNING: [PSU-2]  Parameter : PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_1 has negative value -0.072 . PS DDR interfaces might fail when entering negative DQS skew values.}}

# these don't appear to affect anything
set_msg_config -new_severity INFO -id {BD 41-1731} -string {{WARNING: [BD 41-1731] Type mismatch between connected pins: /clk_wiz_0/clk_out1(clk) and /delorean_lcm_0/CLK_90(undef)}}
set_msg_config -new_severity INFO -id {BD 41-926} -string {{WARNING: [BD 41-926] Following properties on interface pin /delorean_lcm_0/s00_bram have been updated from connected ip. They may not be synchronized with cell properties. You can set property on interface pin directly to confirm the value and resolve the warning.}}
set_msg_config -new_severity INFO -id {BD 41-927} -string {{WARNING: [BD 41-927] Following properties on pin /delorean_lcm_0/s00_axi_aclk have been updated from connected ip. They may not be synchronized with cell properties. You can set property on pin directly to confirm the value and resolve the warning.}}
set_msg_config -new_severity INFO -id {BD 41-927} -string {{WARNING: [BD 41-927] Following properties on pin /delorean_lcm_0/RX_LVDS_CLK_P have been updated from connected ip. They may not be synchronized with cell properties. You can set property on pin directly to confirm the value and resolve the warning.}}
set_msg_config -new_severity INFO -id {BD 41-927} -string {{WARNING: [BD 41-927] Following properties on pin /delorean_lcm_0/RX_LVDS_CLK_N have been updated from connected ip. They may not be synchronized with cell properties. You can set property on pin directly to confirm the value and resolve the warning.}}
set_msg_config -new_severity INFO -id {BD 41-927} -string {{WARNING: [BD 41-927] Following properties on pin /delorean_lcm_0/TX_LVDS_CLK_P have been updated from connected ip. They may not be synchronized with cell properties. You can set property on pin directly to confirm the value and resolve the warning.}}
set_msg_config -new_severity INFO -id {BD 41-927} -string {{WARNING: [BD 41-927] Following properties on pin /delorean_lcm_0/TX_LVDS_CLK_N have been updated from connected ip. They may not be synchronized with cell properties. You can set property on pin directly to confirm the value and resolve the warning.}}
set_msg_config -new_severity INFO -id {BD 41-927} -string {{WARNING: [BD 41-927] Following properties on pin /delorean_lcm_0/ITO_CLK have been updated from connected ip. They may not be synchronized with cell properties. You can set property on pin directly to confirm the value and resolve the warning.}}
set_msg_config -new_severity INFO -id {BD 41-927} -string {{WARNING: [BD 41-927] Following properties on pin /delorean_spi_0/s00_axi_aclk have been updated from connected ip. They may not be synchronized with cell properties. You can set property on pin directly to confirm the value and resolve the warning.}}

# ignore autogenerated stuff
set_msg_config -new_severity INFO -id {IP_Flow 19-4994} -string {{WARNING: [IP_Flow 19-4994] Overwriting existing constraint file} {auto_pc_0_ooc.xdc}}
set_msg_config -new_severity INFO -id {IP_Flow 19-4994} -string {{WARNING: [IP_Flow 19-4994] Overwriting existing constraint file} {auto_pc_1_ooc.xdc}}

# global include file is included multiple times
set_msg_config -new_severity INFO -id {IP_Flow 19-1971} -string {{WARNING: [IP_Flow 19-1971] File named "../../../rtl_src/delorean_defines.v" already exists in file group "xilinx_anylanguagebehavioralsimulation", cannot add it again.}}
set_msg_config -new_severity INFO -id {IP_Flow 19-1971} -string {{WARNING: [IP_Flow 19-1971] File named "../../../rtl_src/delorean_defines.v" already exists in file group "xilinx_anylanguagesynthesis", cannot add it again.}}

# reported because we source ip message filter files in the main project to
# avoid copying contents.
set_msg_config -new_severity INFO -id {Common 17-1361} -string {{WARNING: [Common 17-1361] You have specified a new message control rule that is equivalent to an existing rule with attributes}}

# max path is around 150 characters (not close to 260).
set_msg_config -new_severity INFO -id {IP_Flow 19-4995} -string {{[IP_Flow 19-4995] The host OS only allows 260 characters in a normal path.}}

# -----------------------------------------------------------------------------
# Approved synthesis messages
# -----------------------------------------------------------------------------
# Don't worry about AXI interconnect internals. See Vivado schematics of
# elaborated design (not synthesized design) for details. m0x_couplers appear
# to be pass-throughs so global clock and reset signals aren't used.
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design delorean_axi_interconnect_1_0 has unconnected port M00_ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design delorean_axi_interconnect_1_0 has unconnected port M00_ARESETN}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design delorean_axi_interconnect_1_0 has unconnected port M01_ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design delorean_axi_interconnect_1_0 has unconnected port M01_ARESETN}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design delorean_axi_interconnect_1_0 has unconnected port S00_ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design delorean_axi_interconnect_1_0 has unconnected port S00_ARESETN}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design delorean_axi_interconnect_0_0 has unconnected port M00_ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design delorean_axi_interconnect_0_0 has unconnected port M00_ARESETN}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design delorean_axi_interconnect_0_0 has unconnected port M01_ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design delorean_axi_interconnect_0_0 has unconnected port M01_ARESETN}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design delorean_axi_interconnect_0_0 has unconnected port M02_ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design delorean_axi_interconnect_0_0 has unconnected port M02_ARESETN}}

set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design s00_couplers_imp_1TKPSKM has unconnected port M_ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design s00_couplers_imp_1TKPSKM has unconnected port M_ARESETN}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design s00_couplers_imp_1TKPSKM has unconnected port S_ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design s00_couplers_imp_1TKPSKM has unconnected port S_ARESETN}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design m01_couplers_imp_1XFH0ZP has unconnected port M_ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design m01_couplers_imp_1XFH0ZP has unconnected port M_ARESETN}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design m01_couplers_imp_1XFH0ZP has unconnected port S_ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design m01_couplers_imp_1XFH0ZP has unconnected port S_ARESETN}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design m00_couplers_imp_5XU750 has unconnected port M_ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design m00_couplers_imp_5XU750 has unconnected port M_ARESETN}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design s00_couplers_imp_1XS4E1Y has unconnected port M_ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design s00_couplers_imp_1XS4E1Y has unconnected port M_ARESETN}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design m02_couplers_imp_23PQ7B has unconnected port M_ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design m02_couplers_imp_23PQ7B has unconnected port M_ARESETN}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design m02_couplers_imp_23PQ7B has unconnected port S_ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design m02_couplers_imp_23PQ7B has unconnected port S_ARESETN}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design m01_couplers_imp_1TS1YTH has unconnected port M_ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design m01_couplers_imp_1TS1YTH has unconnected port M_ARESETN}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design m01_couplers_imp_1TS1YTH has unconnected port S_ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design m01_couplers_imp_1TS1YTH has unconnected port S_ARESETN}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design m00_couplers_imp_MH6CK has unconnected port M_ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design m00_couplers_imp_MH6CK has unconnected port M_ARESETN}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design m00_couplers_imp_MH6CK has unconnected port S_ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design m00_couplers_imp_MH6CK has unconnected port S_ARESETN}}

# Indicates that there are no constraints for the design, or it can indicate
# that the used_in flags are set such that the constraints are ignored. This
# later case is used when running synth_design to not write synthesis
# constraints to the resulting checkpoint. Instead, project constraints are
# read when the synthesized design is opened.
set_msg_config -new_severity INFO -id {Constraints 18-5210} -string {{WARNING: [Constraints 18-5210] No constraints selected for write.}}

# CDMA IP issue. PG034 suggests this OK: The IP wrapper/instantiation template
# has the ‘cdma_tvect_out’ port names. It is safe to keep these output pins
# open.
set_msg_config -new_severity INFO -id {Synth 8-5640} -string {{WARNING: [Synth 8-5640] Port 'cdma_tvect_out' is missing in component declaration}}

# -----------------------------------------------------------------------------
# Approved implementation messages
# -----------------------------------------------------------------------------
set_msg_config -new_severity INFO -id {Opt 31-32} -string {{WARNING: [Opt 31-32] Removing redundant IBUF since it is not being driven by a top-level port.} {clk_wiz_0/inst/clkin1_ibufg}}
set_msg_config -new_severity INFO -id {Constraints 18-550} -string {{WARNING: [Constraints 18-550] Could not create 'IBUF_LOW_PWR' constraint because net} {clk_wiz_0/clk_in1} {is not directly connected to top level port.}}
