# -----------------------------------------------------------------------------
# Approved project design messages
# -----------------------------------------------------------------------------
# these are board presets from Avnet for microzed
set_msg_config -new_severity INFO -id {PSU-1} -string {{CRITICAL WARNING: [PSU-1]  Parameter : PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_0 has negative value -0.073 . PS DDR interfaces might fail when entering negative DQS skew values.}}
set_msg_config -new_severity INFO -id {PSU-2} -string {{CRITICAL WARNING: [PSU-2]  Parameter : PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_1 has negative value -0.072 . PS DDR interfaces might fail when entering negative DQS skew values.}}

# ignore autogenerated stuff
set_msg_config -new_severity INFO -id {IP_Flow 19-4994} -string {{WARNING: [IP_Flow 19-4994] Overwriting existing constraint file}}

# called as a result of export_simulation
set_msg_config -new_severity INFO -id {Vivado 12-3672} -string {{WARNING: [Vivado 12-3672] The is_managed property should only be queried on the file object representing this IP. Use the get_files command to access file objects.}}
set_msg_config -new_severity INFO -id {Vivado 12-3670} -string {{WARNING: [Vivado 12-3670] The generate_synth_checkpoint property should only be queried on the file object representing this IP. Use the get_files command to access file objects.}}

# global include file is included multiple times
set_msg_config -new_severity INFO -id {IP_Flow 19-1971} -string {{WARNING: [IP_Flow 19-1971] File named "../../../rtl_src/genesis_defines.v" already exists in file group "xilinx_anylanguagebehavioralsimulation", cannot add it again.}}
set_msg_config -new_severity INFO -id {IP_Flow 19-1971} -string {{WARNING: [IP_Flow 19-1971] File named "../../../rtl_src/genesis_defines.v" already exists in file group "xilinx_anylanguagesynthesis", cannot add it again.}}

# Not working: ignore project management stuff
set_msg_config -new_severity INFO -id {IP_Flow 19-731} -string {{WARNING: [IP_Flow 19-731] File Group 'xilinx_anylanguagesynthesis (Synthesis)':}}
set_msg_config -new_severity INFO -id {IP_Flow 19-731} -string {{WARNING: [IP_Flow 19-731] File Group 'xilinx_anylanguagebehavioralsimulation (Simulation)':}}

# -----------------------------------------------------------------------------
# Approved synthesis messages
# -----------------------------------------------------------------------------
# Don't limit quantity of synthesis messages. Escalate said suppression.
set_msg_config -limit 1000 -id {Synth 8-3331}
set_msg_config -new_severity WARNING -id {Common 17-14}

# Don't worry about AXI interconnect internals. See Vivado schematics of
# elaborated design (not synthesized design) for details. m0x_couplers appear
# to be pass-throughs so global clock and reset signals aren't used.
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design genesis_ps7_0_axi_periph_0 has unconnected port M00_ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design genesis_ps7_0_axi_periph_0 has unconnected port M01_ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design genesis_ps7_0_axi_periph_0 has unconnected port M00_ARESETN}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design genesis_ps7_0_axi_periph_0 has unconnected port M01_ARESETN}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design s00_couplers_imp_} {has unconnected port M_ARESETN}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design s00_couplers_imp_} {has unconnected port M_ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design m00_couplers_imp_} {has unconnected port M_ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design m00_couplers_imp_} {has unconnected port M_ARESETN}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design m00_couplers_imp_} {has unconnected port S_ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design m00_couplers_imp_} {has unconnected port S_ARESETN}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design m01_couplers_imp_} {has unconnected port M_ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design m01_couplers_imp_} {has unconnected port M_ARESETN}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design m01_couplers_imp_} {has unconnected port S_ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design m01_couplers_imp_} {has unconnected port S_ARESETN}}

# Reported when there are no constraints for a top-level cell
set_msg_config -new_severity INFO -id {Constraints 18-5210} -string {{WARNING: [Constraints 18-5210] No constraint will be written out.}}

# Unused flip-flops in RTL
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (write_addr_pp_reg[0]) is unused and will be removed from module genesis_active_mem.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (write_addr_pp_reg[1]) is unused and will be removed from module genesis_active_mem.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (CH1_WR_ACK_reg) is unused and will be removed from module genesis_active_mem.}}

# Unused ports
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design genesis_active_mem has unconnected port CH0_RD_ADDR[1]}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design genesis_active_mem has unconnected port CH0_RD_ADDR[0]}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design genesis_axi_interface has unconnected port S_AXI_AWPROT}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design genesis_axi_interface has unconnected port S_AXI_ARPROT}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design genesis_genesis_ip0_0_0 has unconnected port s00_axi_awprot}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design genesis_genesis_ip0_0_0 has unconnected port s00_axi_arprot}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design genesis_genesis_ip1_0_0 has unconnected port s00_axi_awprot}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design genesis_genesis_ip1_0_0 has unconnected port s00_axi_arprot}}

# -----------------------------------------------------------------------------
# Approved implementation messages
# -----------------------------------------------------------------------------
