# -----------------------------------------------------------------------------
# Approved project design messages
# -----------------------------------------------------------------------------
# these are board presets from Avnet for microzed
set_msg_config -new_severity INFO -id {PSU-1} -string {{CRITICAL WARNING: [PSU-1]  Parameter : PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_0 has negative value -0.073 . PS DDR interfaces might fail when entering negative DQS skew values.}}
set_msg_config -new_severity INFO -id {PSU-2} -string {{CRITICAL WARNING: [PSU-2]  Parameter : PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_1 has negative value -0.072 . PS DDR interfaces might fail when entering negative DQS skew values.}}

# these doesn't appear to affect anything
set_msg_config -new_severity INFO -id {BD 41-1731} -string {{WARNING: [BD 41-1731] Type mismatch between connected pins: /clk_wiz_0/clk_out1(clk) and /orchid_0/CLK_120(undef)}}
set_msg_config -new_severity INFO -id {BD 41-927} -string {{WARNING: [BD 41-927] Following properties on pin /orchid_0/LVDS_CLK_N have been updated from connected ip. They may not be synchronized with cell properties. You can set property on pin directly to confirm the value and resolve the warning.}}
set_msg_config -new_severity INFO -id {BD 41-927} -string {{WARNING: [BD 41-927] Following properties on pin /orchid_0/LVDS_CLK_P have been updated from connected ip. They may not be synchronized with cell properties. You can set property on pin directly to confirm the value and resolve the warning.}}

# ignore autogenerated stuff
set_msg_config -new_severity INFO -id {IP_Flow 19-4994} -string {{WARNING: [IP_Flow 19-4994] Overwriting existing constraint file 'c:/Users/twilliamson/git_repos/zynq_dev/vivado_projects/orchid/orchid.srcs/sources_1/bd/orchid/ip/orchid_auto_pc_0/orchid_auto_pc_0_ooc.xdc'}}

# called as a result of export_simulation
set_msg_config -new_severity INFO -id {Vivado 12-3672} -string {{WARNING: [Vivado 12-3672] The is_managed property should only be queried on the file object representing this IP. Use the get_files command to access file objects.}}
set_msg_config -new_severity INFO -id {Vivado 12-3670} -string {{WARNING: [Vivado 12-3670] The generate_synth_checkpoint property should only be queried on the file object representing this IP. Use the get_files command to access file objects.}}

# -----------------------------------------------------------------------------
# Approved synthesis messages
# -----------------------------------------------------------------------------
# The Master interface of the AXI Interconnect is unused in the design (all
# data flow is downwards).
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design orchid_ps7_0_axi_periph_0 has unconnected port ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design orchid_ps7_0_axi_periph_0 has unconnected port ARESETN}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design orchid_ps7_0_axi_periph_0 has unconnected port M00_ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design orchid_ps7_0_axi_periph_0 has unconnected port M00_ARESETN}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design s00_couplers_imp_7OXCWY has unconnected port M_ACLK}}
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design s00_couplers_imp_7OXCWY has unconnected port M_ARESETN}}

# Constraints that don't apply to synthesis, only to implementation
set_msg_config -new_severity INFO -id {Designutils 20-1567} -string {{WARNING: [Designutils 20-1567] Use of 'set_multicycle_path' with '-hold' is not supported by synthesis. The constraint will not be passed to synthesis.}}

# Reported when there are no constraints for a top-level cell
set_msg_config -new_severity INFO -id {Constraints 18-5210} -string {{WARNING: [Constraints 18-5210] No constraint will be written out.}}

# Input signals unused in RTL module
set_msg_config -new_severity INFO -id {Synth 8-3331} -string {{WARNING: [Synth 8-3331] design orchid_data_mux has unconnected port AXI_MEMORY[}}

# Unused flip-flops in RTL
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (axi_bresp_reg[1]) is unused and will be removed from module orchid_axi_interface.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (axi_awaddr_reg[1]) is unused and will be removed from module orchid_axi_interface.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (axi_awaddr_reg[0]) is unused and will be removed from module orchid_axi_interface.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (axi_araddr_reg[1]) is unused and will be removed from module orchid_axi_interface.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (axi_araddr_reg[0]) is unused and will be removed from module orchid_axi_interface.}}
set_msg_config -new_severity INFO -id {Synth 8-3332} -string {{WARNING: [Synth 8-3332] Sequential element (axi_rresp_reg[1]) is unused and will be removed from module orchid_axi_interface.}}

# These constraints only apply to implementation but I can't directly filter between synth and impl
#set_msg_config -new_severity INFO -id {Vivado 12-508} -string {{WARNING: [Vivado 12-508] No pins matched 'orchid_i/orchid_0/inst/I_orchid_axi_interface/slv_regs_reg\[([0-9]|[1-5][0-9]|6[0-3])\]\[[0-9]+\]/C'.}}
#set_msg_config -new_severity INFO -id {Vivado 12-508} -string {{WARNING: [Vivado 12-508] No pins matched 'orchid_i/orchid_0/inst/I_orchid_core/I_orchid_data_mux/LVDS_DATA_reg[*]/D'.}}
#set_msg_config -new_severity INFO -id {Vivado 12-508} -string {{WARNING: [Vivado 12-508] No pins matched 'orchid_i/orchid_0/inst/I_orchid_axi_interface/slv_regs_reg\[6[89]\]\[[0-9]+\]/C'.}}
#set_msg_config -new_severity INFO -id {Vivado 12-508} -string {{WARNING: [Vivado 12-508] No pins matched 'orchid_i/orchid_0/inst/I_orchid_core/I_orchid_fsm_scan_seq/dwell_expired_reg/D'.}}
#set_msg_config -new_severity INFO -id {Vivado 12-508} -string {{WARNING: [Vivado 12-508] No pins matched 'orchid_i/orchid_0/inst/I_orchid_sync_a2b/a2b_req_reg/C'.}}
#set_msg_config -new_severity INFO -id {Vivado 12-508} -string {{WARNING: [Vivado 12-508] No pins matched 'orchid_i/orchid_0/inst/I_orchid_sync_a2b/a2b_req_sync0_reg/D'.}}
#set_msg_config -new_severity INFO -id {Vivado 12-508} -string {{WARNING: [Vivado 12-508] No pins matched 'orchid_i/orchid_0/inst/I_orchid_sync_a2b/a2b_req_sync1_reg/C'.}}
#set_msg_config -new_severity INFO -id {Vivado 12-508} -string {{WARNING: [Vivado 12-508] No pins matched 'orchid_i/orchid_0/inst/I_orchid_sync_a2b/b2a_ack_sync0_reg/D'.}}
#set_msg_config -new_severity INFO -id {Vivado 12-508} -string {{WARNING: [Vivado 12-508] No pins matched 'orchid_i/orchid_0/inst/I_orchid_axi_interface/slv_regs_reg[71][*]/C'.}}
#set_msg_config -new_severity INFO -id {Vivado 12-508} -string {{WARNING: [Vivado 12-508] No pins matched 'orchid_i/orchid_0/inst/I_orchid_sync_a2b/B_DATA_reg[*]/D'.}}
#set_msg_config -new_severity INFO -id {Vivado 12-508} -string {{WARNING: [Vivado 12-508] No pins matched 'orchid_i/orchid_0/inst/I_orchid_core/I_orchid_fsm_scan_seq/TABLE_SEL_reg[*]*/C'.}}
#set_msg_config -new_severity INFO -id {Vivado 12-508} -string {{WARNING: [Vivado 12-508] No pins matched 'orchid_i/orchid_0/inst/I_orchid_core/I_orchid_data_mux/LVDS_DATA_reg[*]/D'.}}
#set_msg_config -new_severity INFO -id {Vivado 12-180} -string {{WARNING: [Vivado 12-180] No cells matched 'orchid_i/orchid_0/inst/I_orchid_sync_a2b/a2b_req_sync1_reg'.}}
#set_msg_config -new_severity INFO -id {Vivado 12-180} -string {{WARNING: [Vivado 12-180] No cells matched 'orchid_i/orchid_0/inst/I_orchid_sync_a2b/a2b_req_sync2_reg'.}}
#set_msg_config -new_severity INFO -id {Vivado 12-180} -string {{WARNING: [Vivado 12-180] No cells matched 'orchid_i/orchid_0/inst/I_orchid_sync_a2b/b2a_ack_sync0_reg'.}}
#set_msg_config -new_severity INFO -id {Vivado 12-180} -string {{WARNING: [Vivado 12-180] No cells matched 'orchid_i/orchid_0/inst/I_orchid_sync_a2b/b2a_ack_sync1_reg'.}}
#set_msg_config -new_severity INFO -id {Project 1-498} -string {{WARNING: [Project 1-498] One or more constraints failed evaluation while reading constraint file [C:/Users/twilliamson/git_repos/zynq_dev/constraints/orchid_constraints.xdc] and the design contains unresolved black boxes. These constraints will be read post-synthesis (as long as their source constraint file is marked as used_in_implementation) and should be applied correctly then. You should review the constraints listed in the file [.Xil/orchid_wrapper_propImpl.xdc] and check the run log file to verify that these constraints were correctly applied.}}

# -----------------------------------------------------------------------------
# Approved implementation messages
# -----------------------------------------------------------------------------
set_msg_config -new_severity INFO -id {Constraints 18-550} -string {{WARNING: [Constraints 18-550] Could not create 'IBUF_LOW_PWR' constraint because net 'orchid_i/clk_wiz_0/clk_in1' is not directly connected to top level port. Synthesis is ignored for c:/Users/twilliamson/git_repos/zynq_dev/vivado_projects/orchid/orchid.srcs/sources_1/bd/orchid/ip/orchid_clk_wiz_0_0/orchid_clk_wiz_0_0/orchid_clk_wiz_0_0.edf but preserved for implementation. [c:/Users/twilliamson/git_repos/zynq_dev/vivado_projects/orchid/orchid.srcs/sources_1/bd/orchid/ip/orchid_clk_wiz_0_0/orchid_clk_wiz_0_0/orchid_clk_wiz_0_0.edf:314]}}
set_msg_config -new_severity INFO -id {Opt 31-32} -string {{WARNING: [Opt 31-32] Removing redundant IBUF since it is not being driven by a top-level port. orchid_i/clk_wiz_0/inst/clkin1_ibufg}}
